expose container and compose functionality, allow idiomatic compose file, allow setting mine function
salt-formulas/salt-formula-docker pull request #14
Opened 2017-06-29 21:22 UTC by FraaJad

Hi, I found this formula really useful so I added some functionality.

This pull request...
1. maintains backward compatibility
2. container.sls now exposes all dockerng.running parameters
3. container.sls makes volume directory creation optional so single files can be mounted (ie: /var/run/docker.sock)
4. docker-compose.yml
  a. is rendered in pure YAML
  b. adds support for volumes key
  c. allows idiomatic "services" (and "networks") but supports "service" key
  d. supports empty key volume definitions (ie data:)
5. swarm.sls allows setting a different mine.get function.  grains.items can expose sensitive data so grains.item may be used instead.

Cheers,
Doug

###
# Use case example
###

docker:
  host:
    enabled: true
    pkgs:
      - docker-engine=17.05.0*
    options:
      bip: 192.168.129.1/24
      log-driver: json-file
      log-opts:
        max-size: 500m
      dns: 
        - 192.168.129.1
      dns-search: 
        - service.consul
  client:
    enabled: true
    compose:
      source:
        engine: docker
        image: docker/compose:1.14.0

    container:
      registrator:
        image: gliderlabs/registrator:v7
        command: -ip {{ salt.grains.get('ip_interfaces:eth0:0') }} -deregister="on-success" consul://localhost:8500
        network_mode: host
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock
        makedirs: False
        restart_policy: on-failure

      logspout:
        image: vincit/logspout-gelf
        command: gelf://graylog.service.consul:12201
        hostname: {{ grains['id'] }}
        environment:
          BACKLOG: '"false"'
        ports:
          - 8000:80
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        makedirs: False
        restart_policy: on-failure

    compose:
      graylog:
        # Run up action, any positional argument to docker-compose CLI
        # If not defined, only docker-compose.yml is generated
        status: up
        # Run image pull every time state is run triggering container
        # restart in case it's changed
        pull: false
        volumes:
          mongo-db:
          mongo-configdb:
          elasticsearch-data:
          graylog-data:
        service:
          mongo:
            image: mongo:3
            deploy:
              restart_policy:
                condition: on-failure
                max_attempts: 3
            volumes:
              - mongo-db:/data/db
              - mongo-configdb:/data/configdb
          elasticsearch:
            image: elasticsearch:2
            command: elasticsearch -Des.cluster.name='graylog'
            deploy:
              restart_policy:
                condition: on-failure
                max_attempts: 3
            volumes:
              - elasticsearch-data:/usr/share/elasticsearch/data
          server:
            image: graylog2/server:2.1.1-1
            deploy:
              restart_policy:
                condition: on-failure
                max_attempts: 3
            volumes:
              - graylog-data:/usr/share/graylog/data
            environment:
              GRAYLOG_PASSWORD_SECRET: somepasswordpepper
              GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
              SERVICE_9000_NAME: graylog
              SERVICE_12201_NAME: gelf-udp
            links:
              - mongo
              - elasticsearch
            ports:
              - 9000:9000
              - 12201:12201/udp

2017-06-29 21:22 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2017-06-30 08:14 UTC, fpytloun requested changes
Thank you for your contribution, I like the change :-)

Ad. singular vs. plural in pillar, we use following convention:
- singular for dictionary (eg. service) because it makes more sense to refer service.mysvc (so you can naturally say "service mysvc")
- plural for lists (eg. services) so you can naturally say "first item of list of services"

So I would prefer keeping this convention.

2017-06-30 08:14 UTC, fpytloun commented on docker/map.jinja
>      'default': {
Don't need to change map.jinja mode (add execute bit), leave it 644

2017-06-30 20:38 UTC, FraaJad commented
Right on!  No problem, the naming convention makes sense.  And the changes have been made.

> On Jun 30, 2017, at 1:14 AM, Filip Pytloun <notifications@github.com> wrote:
> 
> @fpytloun requested changes on this pull request.
> 
> Thank you for your contribution, I like the change :-)
> 
> Ad. singular vs. plural in pillar, we use following convention:
> 
> singular for dictionary (eg. service) because it makes more sense to refer service.mysvc (so you can naturally say "service mysvc")
> plural for lists (eg. services) so you can naturally say "first item of list of services"
> So I would prefer keeping this convention.
> 
> In docker/map.jinja <https://github.com/salt-formulas/salt-formula-docker/pull/14#discussion_r124985510>:
> 
> > @@ -22,7 +22,8 @@
>      'default': {
> Don't need to change map.jinja mode (add execute bit), leave it 644
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/salt-formulas/salt-formula-docker/pull/14#pullrequestreview-47329800>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AUVeDVK78YCdymsBVjQd52Lyp97GCKSSks5sJK5VgaJpZM4OJ4kt>.
>

2017-07-10 22:36 UTC, FraaJad commented on docker/map.jinja
>      'default': {
Fixed, with a couple other small corrections

2017-07-13 15:07 UTC, merged